// <auto-generated />
namespace Ventas.Infraestructura.ContextoDeDatos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class UsuarioCorreo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UsuarioCorreo));
        
        string IMigrationMetadata.Id
        {
            get { return "201909140301162_UsuarioCorreo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
